### ISSUE TITLE
"Start looking here" changes automatically restart the search

### ISSUE THREAD

**Issue by norberturkiewicz** [aplteam/Fire#6]
I don't think this is a good behavior.  Changing the start path should not reevaluate the search without an explicit button click.

**Comment by aplteam** [comment]
Not so sure. When you enter
```
]a
```
in the Dyalog session it's executed straight away as well. Same in Fire, it's just that <enter> triggers the default button.

If you want to actually select a line from the autocomplete form then you have to press <cursor+right> in both Fire and the Dyalog session, and that works fine.

And BTW, it has been this way since day one.

Any other opinions?

**Comment by aplteam** [comment]
Fixed
