### ISSUE TITLE
Help ReadMe and Useful RegEx fail to find file

### ISSUE THREAD

**Issue by norberturkiewicz** [aplteam/Fire#9]
Both the help options fail.  Build 6.6.3.5

![image](https://user-images.githubusercontent.com/5807754/49178113-87eaaf00-f314-11e8-909e-ab24b7cc5959.png)

![image](https://user-images.githubusercontent.com/5807754/49178131-946f0780-f314-11e8-8e53-9ecdc8ef1193.png)

**Comment by aplteam** [comment]
Fire is not able to find those HTML files anywhere but in one of:

* a folder "Fire" which is a sibling of the user command script. That folder will exist, and it contains the workspace Fire.dws, otherwise Fire cannot work. Make sure the HTML file accompany the WS and you will be fine
* In a folder "Fire" that lives in the installation folder of your version of Dyalog (not recommended).

Your screenshot shows a git project "Fire", but of course Fire cannot have any knowledge about that.

**Comment by norberturkiewicz** [comment]
I extract the downloaded Fire application into a folder called dist in the project folder.  I am not using the actual git project to run fire.

**Comment by aplteam** [comment]
But that cannot work. The fire script as well as the folder with the WS and
the HTML files must live in one of the folders scanned by the interpreter
for user commands.

There are just two defaults:

1. The folder SALT\spice in the Dyalog installation folder
2. The folder Documents\MyUCMDs in your home folder which normally is
C:\Users\{YourUserName}\

Any other folder would need to be added to the Source folders on the "User
Commands" tab in the configuration dialog box.

**Comment by norberturkiewicz** [comment]
Do I not have fire installed correctly?

![image](https://user-images.githubusercontent.com/5807754/49593064-525b4c80-f938-11e8-825f-cfd2f942c187.png)

![image](https://user-images.githubusercontent.com/5807754/49593098-6737e000-f938-11e8-98f5-c16ca3828a2c.png)

![image](https://user-images.githubusercontent.com/5807754/49593120-7028b180-f938-11e8-8bea-69a3ab40e4a7.png)
